name: Provisioning

on: push

permissions:
  contents: read

jobs:
  provisioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Formatting
        run: terraform fmt -recursive -check || true

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: terraform plan -var-file="environment/dev.tfvars"

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.44.1

      - name: Linting
        run: |
          tflint --version
          tflint --init
          tflint --config=.tflint.hcl --chdir=./

      - name: TFSec Scan
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          additional_args: "--force-all-dirs"
          soft_fail: true


    # - name: Terraform Apply
    #   working-directory: ./terraform/
    #   if: github.ref == 'refs/heads/main'
    #   run: |
    #       terraform apply  -auto-approve -no-color -var-file=environment/sandbox.tfvars \
    #         -var "access_key=${{ secrets.AWS_ACCESS_KEY }}" \
    #         -var "secret_key=${{ secrets.AWS_SECRET_KEY }}"